version: '3'
services:

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: bancosiga
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: banco
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - SIGA_net

  application:
    build: .
    ports:
      - "8085:8085"
    networks:
      - SIGA_net
    command: python3 -m http.server 8080

networks:
  SIGA_net: