version: '3'
services:
  application:
    build: .
    ports:
      - "8085:8085"
    networks:
      - SIGA_net

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: bancosiga
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: banco
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      - SIGA_net

networks:
  SIGA_net: